[[redirects]]
  from = "/hackaday"
  to = "https://blog.benjames.io/hackaday"

[[redirects]]
  from = "/contact"
  to = "/"

[[redirects]]
  from = "/iot-chess-board"
  to = "https://blog.benjames.io/contact"

[[redirects]]
  from = "/about"
  to = "/"



[[redirects]]
  from = "/page/*"
  to = "https://blog.benjames.io/page/:splat"

[[redirects]]
  from = "/2020/*"
  to = "https://blog.benjames.io/2020/:splat"

[[redirects]]
  from = "/2019/*"
  to = "https://blog.benjames.io/2019/:splat"

[[redirects]]
  from = "/2018/*"
  to = "https://blog.benjames.io/2018/:splat"

[[redirects]]
  from = "/2017/*"
  to = "https://blog.benjames.io/2017/:splat"

[[redirects]]
  from = "/2016/*"
  to = "https://blog.benjames.io/2016/:splat"

[[redirects]]
  from = "/2015/*"
  to = "https://blog.benjames.io/2015/:splat"

[[redirects]]
  from = "/2014/*"
  to = "https://blog.benjames.io/2014/:splat"